#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := liteplayer

EXTRA_COMPONENT_DIRS = ../../components

include $(ADF_PATH)/make/project.mk
